name: satay-analysis
channels:
  - defaults
  - conda-forge
dependencies:
  - conda
  - python=3.7
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator
  - navigator-updater
  - pandoc
  - pip
  - jupyterlab
  - matplotlib
  - gseapy
  - glueviz
  - cookiecutter
  - pandas
  - openpyxl
  - jedi
  - networkx

